version: '3.4'
services:
  node:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile.local
      network: host
    volumes:
      - .:/usr/src/app
    env_file: ./env/local.env
    network_mode: host 
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.6-bionic
    restart: on-failure
    network_mode: host 
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_PORT=27017
volumes:
    data: